export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const VALIDAR_PRODUCTO = "VALIDAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";
export const OBTENER_PRODUCTO = "OBTENER_PRODUCTO";