export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const VALIDAR_PRODUCTO = "VALIDAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";
export const OBTENER_PRODUCTO = "OBTENER_PRODUCTO";

export const AÑADIR_CARRITO = "AÑADIR_CARRITO";
export const ELIMINAR_CARRITO = "ELIMINAR_CARRITO";
export const OBTENER_CARRITO = "OBTENER_CARRITO";
export const TOTAL_CARRITO = "TOTAL_CARRITO";
