export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const VALIDAR_PRODUCTO = "VALIDAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";
export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS";

export const AÑADIR_CARRITO = "AÑADIR_CARRITO";
export const ELIMINAR_CARRITO = "ELIMINAR_CARRITO";
export const MOSTRAR_CARRITO = "MOSTRAR_CARRITO";
export const TOTAL_CARRITO = "TOTAL_CARRITO";
